version: "{build}"

os:
  - Visual Studio 2015

init:
  - git config --global core.autocrlf input

install:
  - git submodule update --init --recursive

platform:
  - x64

configuration:
  - Debug
  - Release

before_build:
  - cmake -H. -BBuild -A%PLATFORM%

build:
  project: Build\ModernCppCI.sln       
  parallel: true                    
  verbosity: normal                   

test_script:
  - cd Build
  - ctest -V -j 2 -C %CONFIGURATION%
